# null -> default

# Data
data:
  root: datasets/MMAD
  output_root: ./output

# Anomaly Detection Model
anomaly:
  model: efficientad  # patchcore | winclip | efficientad

  patchcore:
    backbone: null
    layers: null
    coreset_sampling_ratio: null

  winclip:
    class_name: null
    k_shot: null
    scales: null

  efficientad:
    model_size: null
    teacher_out_channels: null
    visualizer: false
    evaluator: true
    imagenet_dir: imagenette/train

# Training
training:
  train_batch_size: null
  eval_batch_size: null
  num_workers: 0 # Colab A100 기준 4~10 권장
  max_epochs: 30  # EfficientAd는 빠른 수렴, 부족하면 추가 학습 가능

# Engine
engine:
  accelerator: cpu  # auto | cpu | gpu | mps # Mac은 cpu 권장 mps 호환성 문제 심함
  enable_progress_bar: false  # true면 Colab에서 tqdm/rich 충돌로 RecursionError 발생
  logger: wandb  # false | wandb

# WandB
wandb:
  project: "Anomaly_Detection"

# Output
output:
  save_json: true